### ISSUE TITLE
Window Size

### ISSUE THREAD

**Issue by kimbtech** [Malte311/FinanceList-Desktop#70]
**Describe the bug**

After changing the window size in the settings, the windows stays in the same size. One has to restart the program to get the new smaller size.

**To Reproduce**

1. Open tool
2. Go to Setting
3. Change Window size to the maximum
4. Change the size to a smaller one
5. The window stays the same

**Expected behavior**

After changing the size, the window should resize to the new one.

**Desktop (please complete the following information):**

 - OS: linux mint
 - Version 1.0.2 alpha

**Comment by Malte311** [comment]
Idea: Remove the given window sizes completely and let the user resize/minimize/maximize the window as he or she likes to. After each resize, save the current size and on the next start keep that size.
